spring.application.name=hotelhub

spring.datasource.url=jdbc:postgresql://localhost:5432/hotelhub
spring.datasource.username=hotelhub
spring.datasource.password=duy123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

server.error.include-message=always

jwt.secret=hotelhub_super_secret_key_hotelhub_super_secret_key
jwt.access-token-expiration=86400000
jwt.refresh-token-expiration=604800000
